spring:
  flyway:
    table: schema_version_history
  profiles:
    active: dev
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deletedAt
      logic-delete-value: "now()"
      logic-not-delete-value: "null"

