server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/lucian_blog
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeEnumsPackage: com.lucian.lucian_blog.bean.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: admin123456
  bucketName: pic



