spring:
  flyway:
    table: schema_version_history
  profiles:
    active: @profiles.active@
logging:
  config: classpath:log4j2.xml
  level:
    com.lucian: @logging.level@
    org.springframework: warn
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deletedAt
      logic-delete-value: "now()"
      logic-not-delete-value: "null"
server:
  servlet:
    context-path: /admin

